In [1]:
import torch
import numpy as np

In [2]:
e_d = torch.rand(5,5)

edge_cout = torch.zeros_like(e_d)
values, indices = e_d.topk(
    4, dim=0, largest=True, sorted=True)

edge_cout = edge_cout.scatter(
    dim=0, index=indices, value=1)
edge_list = edge_cout.nonzero()

edge_cout

tensor([[1., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1.],
        [0., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [17]:
e_d = torch.rand(5,5)
e_d = e_d.reshape(-1)
e_d


tensor([0.7474, 0.2365, 0.9989, 0.9448, 0.9322, 0.0903, 0.0397, 0.9250, 0.3702,
        0.1154, 0.3460, 0.9418, 0.8518, 0.7123, 0.5954, 0.4300, 0.4361, 0.3519,
        0.1706, 0.4948, 0.1689, 0.1688, 0.7522, 0.3829, 0.5658])

In [30]:
values, indices = e_d.topk(
    int(e_d.shape[0]/2), dim=0, largest=True, sorted=False)
indices

tensor([ 2,  3, 11,  4,  7, 12, 22,  0, 13, 14, 24, 19])

In [31]:
edge_cout = torch.zeros_like(e_d)
edge_cout = edge_cout.scatter(
    dim=0, index=indices, value=1)
edge_cout

tensor([1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 1., 0., 0., 1., 0., 1.])

In [32]:
edge_cout = edge_cout.reshape(5,5)
edge_cout

tensor([[1., 0., 1., 1., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 1.]])