In [2]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
plt.figure(dpi=120)
x = range(0,100)
y = np.random.random(100)
plt.plot(x, y, color='red',  label='random(x)')
plt.legend() #绘制图例
plt.xlabel('x')
plt.ylabel('f(x)')

In [3]:
def heatmap(data, row_labels, col_labels, ax=None,
            cbar_kw={}, cbarlabel="", **kwargs):
    """
    Create a heatmap from a numpy array and two lists of labels.

    Parameters
    ----------
    data
        A 2D numpy array of shape (N, M).
    row_labels
        A list or array of length N with the labels for the rows.
    col_labels
        A list or array of length M with the labels for the columns.
    ax
        A `matplotlib.axes.Axes` instance to which the heatmap is plotted.  If
        not provided, use current axes or create a new one.  Optional.
    cbar_kw
        A dictionary with arguments to `matplotlib.Figure.colorbar`.  Optional.
    cbarlabel
        The label for the colorbar.  Optional.
    **kwargs
        All other arguments are forwarded to `imshow`.
    """

    if not ax:
        ax = plt.gca()

    # Plot the heatmap
    im = ax.imshow(data, **kwargs)

    # Create colorbar
    cbar = ax.figure.colorbar(im, ax=ax, **cbar_kw)
    cbar.ax.set_ylabel(cbarlabel, rotation=-90, va="bottom")

    # We want to show all ticks...
    ax.set_xticks(np.arange(data.shape[1]))
    ax.set_yticks(np.arange(data.shape[0]))
    # ... and label them with the respective list entries.
    ax.set_xticklabels(col_labels)
    ax.set_yticklabels(row_labels)

    # Let the horizontal axes labeling appear on top.
    ax.tick_params(top=True, bottom=False,
                   labeltop=True, labelbottom=False) 

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=-30, ha="right",
             rotation_mode="anchor")

    # Turn spines off and create white grid.
    # ax.spines[:].set_visible(False)
    ax.spines['top'].set_visible(False) #去掉上边框
    ax.spines['bottom'].set_visible(False) #去掉下边框
    ax.spines['left'].set_visible(False) #去掉左边框
    ax.spines['right'].set_visible(False) #去掉右边框


    ax.set_xticks(np.arange(data.shape[1]+1)-.5, minor=True)
    ax.set_yticks(np.arange(data.shape[0]+1)-.5, minor=True)
    ax.grid(which="minor", color="w", linestyle='-', linewidth=3)
    ax.tick_params(which="minor", bottom=False, left=False)

    return im, cbar

In [ ]:
fig, ax = plt.subplots(dpi = 200)
data = np.random.random([2,10])
im = ax.imshow(data, cmap = 'viridis')

In [ ]:
import seaborn as sns
uniform_data = np.random.randn(2, 12)
ax = sns.heatmap(uniform_data, center=0, cmap="YlGnBu")


In [ ]:
p = [1,2,3]
for i in range(3) :
    p[i] = 'c'+str(i)
p

In [ ]:
signal = np.random.randn(2,12)
cam = np.random.randn(2,12)
chn_num = signal.shape[0]
# channel = np.reshape(np.arange(1, chn_num+1), [-1,1])
channel = list(range(1, chn_num+1))
for i in range(1, chn_num+1):
    channel[i-1] = 'c'+ str(i)
time = np.arange(1,signal.shape[1]+1)
time = np.reshape(time, [1,signal.shape[1]])

# signal = np.expand_dims(signal, axis=0)
# cam = np.expand_dims(cam, axis=0)
# time = np.expand_dims(time, axis=0)
data = np.concatenate((signal, cam),axis=0)
df = pd.DataFrame(data=data.T, columns = pd.MultiIndex.from_product([['signal', 'cam'], channel]))
df['time'] = time.T.astype(np.float16)
df
# data

In [ ]:
['c1','c2']
aa = df['signal','c1'].values
aa = np.reshape(aa, (12,1))
aa

In [ ]:
x= np.linspace(0.5,11.5,12)
x

In [ ]:
a = np.reshape(df['cam','c1'].values, (1,12))
ax = sns.heatmap(a, center=0, cmap="YlGnBu", yticklabels=['c1'])
a = np.reshape(df['cam','c2'].values, (1,12))
ax3 = sns.heatmap(a, center=0, cmap="YlGnBu", yticklabels=['c2'])
ax3 = ax.twinx()
ax2 = ax.twinx()
ax2 = sns.lineplot(x= np.linspace(0.5,11.5,12), y = 'c1',data=df['signal'], color='red', sort=False)
plt.ylim(-3,3)
plt.show()

In [ ]:
fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True, sharey=True, dpi = 200)
a = np.reshape(df['cam','c1'].values, (1,12))
ax11 = sns.heatmap(a, center=0, cmap="YlGnBu", yticklabels=['c1'])
ax12 = sns.lineplot(x= np.linspace(0.5,11.5,12), y = 'c1',data=df['signal'], color='red', sort=False)
ax12 = ax11.twinx()
ax1.imshow(ax11)
ax1.imshow(ax12)

a = np.reshape(df['cam','c2'].values, (1,12))
ax2 = sns.heatmap(a, center=0, cmap="YlGnBu", yticklabels=['c2'])
ax21 = ax2.twinx()
ax21 = sns.lineplot(x= np.linspace(0.5,11.5,12), y = 'c2',data=df['signal'], color='red', sort=False)
plt.ylim(-3,3)
plt.subplots_adjust(wspace=0, hspace=0)
plt.show()

In [ ]:
fig = plt.figure() 
ax1 = fig.add_axes([0.1, 0.5, 0.8, 0.4], 
                    xticklabels=[], ylim=(-3, 3)) 
ax1.set(ylabel='c1')
ax2 = fig.add_axes([0.1, 0.1, 0.8, 0.4], 
                    ylim=(-10, 10))
a = np.reshape(df['cam','c1'].values, (1,12))
im = ax1.imshow(a, cmap = 'seismic', aspect='auto',extent=(0,12,-3,3),interpolation= 'bilinear')
ax1.plot(np.linspace(0.5,11.5,12), df['signal','c1'], color = 'green')

im = ax2.imshow(a, cmap = 'seismic', aspect='auto',extent=(0,12,-3,3))
ax2.plot(np.linspace(0.5,11.5,12), df['signal','c1'], color = 'green')
plt.show()

In [4]:
def line_heatmap(y_line, y_heat, y_name, fig, i):
    """
        用于画折线-热力图
        y_line,y_heat 为 np.array, shape = [-1] or [1,-1]
    """
    ylim=(-30, 30) # -3,3 根据情况还得改
    ax1 = fig.add_axes([0.1, 0.1+i*0.45, 2.4, 0.4], 
                    xticklabels=[], ylim=ylim) 
    ax1.set(ylabel='c{0}'.format(i))

    y_heat = np.reshape(y_heat,(1,-1))
    y_line = np.reshape(y_line,(-1,1))
    # im = ax1.imshow(y_heat, cmap = 'viridis', aspect='auto',extent=(0,y_heat.shape[1],ylim[0],ylim[1]),interpolation= 'bilinear')
    im = ax1.imshow(y_heat, cmap = 'viridis', aspect='auto',extent=(0,y_heat.shape[1],ylim[0],ylim[1]))
    lens = y_heat.shape[1]
    ax1.plot(np.linspace(0.5,lens-0.5,lens), y_line, color = 'red')
    # ax1.spines['bottom'].set_visible(False) #去掉下边框
    ax1.set_xticks([])

    ax1.figure.colorbar(im, ax=ax1)
    # cbar.ax.set_ylabel(cbarlabel, rotation=-90, va="bottom")

In [ ]:
fig = plt.figure() 
for i in range(4):
    signal = np.random.randn(1,22)
    cam = np.random.randn(1,22)
    line_heatmap(y_line=signal, y_heat=cam, y_name='c{0}'.format(i), fig=fig, i=i)
plt.show()

# 实际操作

In [5]:
data = np.load('E:\\DATABASE\\FirstGNN\\signal\\signal.npy', allow_pickle=True)
n_data = data[0, 0] #dzq 的数据
# for j in range(n_data.shape[0]): # 分类数目
    # n1 = n_data[j, 0] 

In [6]:
data2 = np.load('E:\\DATABASE\\FirstGNN\\CT\\CT-GNN-5.npz')

# cam = data2['cam_list']
# cam.shape

In [29]:
type(data2)

numpy.lib.npyio.NpzFile

In [14]:
cam = data2['n_cam_list']

In [9]:
cam.shape

(1875, 18, 128)

In [15]:
mask = cam>0
cam = mask*cam

In [16]:
def normalization(data):
    _range = np.max(data) - np.min(data)
    return (data - np.min(data)) / _range

In [17]:
cam = normalization(cam)

In [13]:
ad = np.concatenate((cam[0],cam[1],cam[2]), axis=1)
ad.shape

(18, 384)

In [10]:
label_list = data2['label_list']

In [11]:
logits_list = data2['logits_list']
logits_list.shape

(1875, 1, 5)

In [12]:
result = np.argmax(logits_list, axis=2)
result.shape

(1875, 1)

In [45]:
result[1]

array([0], dtype=int64)

In [19]:
label_list.shape

(1875, 1, 1)

In [47]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate((a,b),axis = 0) 
mask = a>1
a = a*mask
a

array([0, 2])

In [22]:
n1 = n_data[0,0]
n11 = n1[0,0]
dn = n11[0,:]
n1.shape,n11.shape, dn.shape

((101, 1), (18, 244), (244,))

In [25]:
n1.shape,n_data.shape

((101, 1), (5, 1))

In [42]:
fig = plt.figure() 
for j in range(n_data.shape[0]):#n_data.shape[0]): # 分类数目
# j=2
    n1 = n_data[j,0] # 1-level
    if n1.shape[0]>125:
        n1_num = 125
    else:
        n1_num = n1.shape[0]
    for k in range(n1_num):#n1.shape[0]):
        n11 = n1[k,0] # 2-level
        it = int(j*375 + k*3)
        cam1 = np.concatenate((cam[it], cam[it+1],cam[it+2]),axis = 1)
        for i in range(18):# n11.shape[0]): # 行的部分，cam 与 signal一致
            if n11.shape[1]>cam1.shape[1]:
                end_trick1 = cam1.shape[1]
            else:
                end_trick1 = n11.shape[1]
            line_heatmap(y_line=n11[i,0:end_trick1], y_heat=cam1[i,0:end_trick1], y_name='c{0}'.format((i+1)), fig=fig, i=i)
        if label_list[it][0,0] == result[it][0]:
            istrue = 'T'
        else:
            istrue = 'F'
        namestr = 'lb{0}_num{1}_{2}'.format(label_list[it][0,0], k, istrue)
        # plt.show()
        f = plt.gcf()
        f.savefig('E:\\DATABASE\\FirstGNN\\cam\\line_heat\\dzq\\f0\\{0}.png'.format(namestr), facecolor='white',dpi=200, bbox_inches='tight',transparent=False)
        f.clear()

<Figure size 432x288 with 0 Axes>

In [28]:
n_data[2,0].shape

(30, 1)

In [35]:
lali = pd.DataFrame(np.reshape(label_list,[-1,1]))

In [36]:
lali.describe()

0
count  1875.000000
mean      2.000000
std       1.414591
min       0.000000
25%       1.000000
50%       2.000000
75%       3.000000
max       4.000000

In [37]:
lb1d = np.reshape(label_list,-1)

In [41]:
np.where(lb1d==3)

(array([1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135,
        1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146,
        1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157,
        1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168,
        1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179,
        1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190,
        1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201,
        1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212,
        1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223,
        1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234,
        1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245,
        1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256,
        1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267,
        1268, 1269, 1270, 1271, 1272, 